### ISSUE TITLE
zbase32 should have no padding

### ISSUE THREAD

**Issue by internalG** [alanblevins/anybase32#3]
>>> anybase32.decode(b'y', anybase32.ZBASE32)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/suwei/Documents/python3env/scrapy/lib/python3.6/site-packages/anybase32/__init__.py", line 102, in decode
    return base64.b32decode(encoded)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/base64.py", line 246, in b32decode
    raise binascii.Error('Incorrect padding')
binascii.Error: Incorrect padding

According to the paper https://philzimmermann.com/docs/human-oriented-base-32-encoding.txt no padding is a feature for zbase32.

**Comment by internalG** [comment]
and some test in paper is not good.
>>> anybase32.decode(b'4t7ye', anybase32.ZBASE32)
b'\xd4z\x04'

#bits base-2                           base32     base64     z-base-32
----- ------                           ------     ------     ---------
1     0                                AA======   AA==       y
1     1                                QA======   gA==       o
2     01                               IA======   QA==       e
2     11                               QA======   gA==       a
10    0000000000                       AAAA====   AAA=       yy
10    1000000010                       QCAA====   gIA=       on
20    10001011100010001000             BC4IQ===   CLiI       tqre
24    111100001011111111000111         6C74O===   8L/H       6n9hq
24    110101000111101000000100         2R5AI===   1HoE       4t7ye
30    111101010101011110111101000011   HVK66QY=   PVXvQw==   6im5sd
